# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  go-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24.x"

    - name: Run
      run: |
        go build -v .
        ./getaduck
    - name: Test
      run: |
        sudo apt-get install moreutils -y
        make test
    - name: Checks
      run: |
        make checks

  other-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.25.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run
        run: |
          go build -v .
          ./getaduck
      - name: Test
        run: make short-test